spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.ip:localhost}:3306/${db.schema:ERI}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${db.username:root}
    password: ${db.password:password}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  data:
    redis:
      host: ${redis.host:localhost}
      port: 6379
      username: ${redis.username:}
      password: ${redis.password:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ibkcloud.eoc.dao.dto
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: null

# 로깅 설정
logging:
  level:
    com.ibkcloud.eoc: DEBUG
    org.springframework.web: DEBUG
    org.mybatis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

# 메시지 설정
spring:
  messages:
    basename: message/messages
    encoding: UTF-8 