-- ========== 대시보드 관리(8) ========== 

CREATE TABLE TB_DLY_EMP_RGT_USE_STS (
    BASE_DT      DATE         NOT NULL COMMENT '기준일자 (PK)',
    EMP_ID       VARCHAR(255) NOT NULL COMMENT '직원번호 (PK)',
    DEPT_CD      VARCHAR(20)  NOT NULL COMMENT '부서코드 (PK)',
    POS_CD       VARCHAR(20)  NOT NULL COMMENT '직급코드 (PK)',
    GENDER_CD    VARCHAR(10)  NOT NULL COMMENT '성별코드 (PK)',
    PGM_USE_CNT  INT          NULL     COMMENT '프로그램 이용건수',
    MCHR_USE_CNT INT          NULL     COMMENT '마음검진 이용건수',
    CNSL_USE_CNT INT          NULL     COMMENT '상담 이용건수',
    PRIMARY KEY (BASE_DT, EMP_ID, DEPT_CD, POS_CD, GENDER_CD)
) COMMENT '일자별 직원권익 이용 현황';

CREATE TABLE TB_MTH_EMP_RGT_USE_STS (
    BASE_YM      VARCHAR(6)   NOT NULL COMMENT '기준년월 (PK)',
    EMP_ID       VARCHAR(255) NOT NULL COMMENT '직원번호 (PK)',
    DEPT_CD      VARCHAR(20)  NOT NULL COMMENT '부서코드 (PK)',
    POS_CD       VARCHAR(20)  NOT NULL COMMENT '직급코드 (PK)',
    GENDER_CD    VARCHAR(10)  NOT NULL COMMENT '성별코드 (PK)',
    PGM_USE_CNT  INT          NULL     COMMENT '프로그램 이용건수',
    MCHR_USE_CNT INT          NULL     COMMENT '마음검진 이용건수',
    CNSL_USE_CNT INT          NULL     COMMENT '상담 이용건수',
    PRIMARY KEY (BASE_YM, EMP_ID, DEPT_CD, POS_CD, GENDER_CD)
) COMMENT '월별 직원권익 이용 현황';

CREATE TABLE TB_DLY_MCHR_USE_STS (
    BASE_DT      DATE         NOT NULL COMMENT '기준일자 (PK)',
    MCHR_TY_CD   VARCHAR(20)  NOT NULL COMMENT '마음검진종류코드 (PK)',
    DEPT_CD      VARCHAR(20)  NOT NULL COMMENT '부서코드 (PK)',
    POS_CD       VARCHAR(20)  NOT NULL COMMENT '직급코드 (PK)',
    GENDER_CD    VARCHAR(10)  NOT NULL COMMENT '성별코드 (PK)',
    EMP_ID       VARCHAR(255) NOT NULL COMMENT '직원번호 (PK)',
    USE_CNT      INT          NULL     COMMENT '이용건수',
    PRIMARY KEY (BASE_DT, MCHR_TY_CD, DEPT_CD, POS_CD, GENDER_CD, EMP_ID)
) COMMENT '일자별 마음검진 이용 현황';

CREATE TABLE TB_MTH_MCHR_USE_STS (
    BASE_YM      VARCHAR(6)   NOT NULL COMMENT '기준년월 (PK)',
    MCHR_TY_CD   VARCHAR(20)  NOT NULL COMMENT '마음검진종류코드 (PK)',
    DEPT_CD      VARCHAR(20)  NOT NULL COMMENT '부서코드 (PK)',
    POS_CD       VARCHAR(20)  NOT NULL COMMENT '직급코드 (PK)',
    GENDER_CD    VARCHAR(10)  NOT NULL COMMENT '성별코드 (PK)',
    EMP_ID       VARCHAR(255) NOT NULL COMMENT '직원번호 (PK)',
    USE_CNT      INT          NULL     COMMENT '이용건수',
    PRIMARY KEY (BASE_YM, MCHR_TY_CD, DEPT_CD, POS_CD, GENDER_CD, EMP_ID)
) COMMENT '월별 마음검진 이용 현황';

CREATE TABLE TB_DLY_PGM_USE_STS (
    BASE_DT      DATE         NOT NULL COMMENT '기준일자 (PK)',
    PGM_ID       VARCHAR(20)  NOT NULL COMMENT '프로그램코드 (PK)',
    DEPT_CD      VARCHAR(20)  NOT NULL COMMENT '부서코드 (PK)',
    POS_CD       VARCHAR(20)  NOT NULL COMMENT '직급코드 (PK)',
    GENDER_CD    VARCHAR(10)  NOT NULL COMMENT '성별코드 (PK)',
    EMP_ID       VARCHAR(255) NOT NULL COMMENT '직원번호 (PK)',
    USE_CNT      INT          NULL     COMMENT '이용건수',
    PRIMARY KEY (BASE_DT, PGM_ID, DEPT_CD, POS_CD, GENDER_CD, EMP_ID)
) COMMENT '일자별 프로그램 이용 현황';

CREATE TABLE TB_MTH_PGM_USE_STS (
    BASE_YM      VARCHAR(6)   NOT NULL COMMENT '기준년월 (PK)',
    PGM_ID       VARCHAR(20)  NOT NULL COMMENT '프로그램코드 (PK)',
    DEPT_CD      VARCHAR(20)  NOT NULL COMMENT '부서코드 (PK)',
    POS_CD       VARCHAR(20)  NOT NULL COMMENT '직급코드 (PK)',
    GENDER_CD    VARCHAR(10)  NOT NULL COMMENT '성별코드 (PK)',
    EMP_ID       VARCHAR(255) NOT NULL COMMENT '직원번호 (PK)',
    USE_CNT      INT          NULL     COMMENT '이용건수',
    PRIMARY KEY (BASE_YM, PGM_ID, DEPT_CD, POS_CD, GENDER_CD, EMP_ID)
) COMMENT '월별 프로그램 이용 현황';

CREATE TABLE TB_DLY_CNSL_USE_STS (
    BASE_DT      DATE         NOT NULL COMMENT '기준일자 (PK)',
    CNSL_TY_CD   VARCHAR(20)  NOT NULL COMMENT '상담종류코드 (PK)',
    DEPT_CD      VARCHAR(20)  NOT NULL COMMENT '부서코드 (PK)',
    POS_CD       VARCHAR(20)  NOT NULL COMMENT '직급코드 (PK)',
    GENDER_CD    VARCHAR(10)  NOT NULL COMMENT '성별코드 (PK)',
    EMP_ID       VARCHAR(255) NOT NULL COMMENT '직원번호 (PK)',
    USE_CNT      INT          NULL     COMMENT '이용건수',
    PRIMARY KEY (BASE_DT, CNSL_TY_CD, DEPT_CD, POS_CD, GENDER_CD, EMP_ID)
) COMMENT '일자별 상담 이용 현황';

CREATE TABLE TB_MTH_CNSL_USE_STS (
    BASE_YM      VARCHAR(6)   NOT NULL COMMENT '기준년월 (PK)',
    CNSL_TY_CD   VARCHAR(20)  NOT NULL COMMENT '상담종류코드 (PK)',
    DEPT_CD      VARCHAR(20)  NOT NULL COMMENT '부서코드 (PK)',
    POS_CD       VARCHAR(20)  NOT NULL COMMENT '직급코드 (PK)',
    GENDER_CD    VARCHAR(10)  NOT NULL COMMENT '성별코드 (PK)',
    EMP_ID       VARCHAR(255) NOT NULL COMMENT '직원번호 (PK)',
    USE_CNT      INT          NULL     COMMENT '이용건수',
    PRIMARY KEY (BASE_YM, CNSL_TY_CD, DEPT_CD, POS_CD, GENDER_CD, EMP_ID)
) COMMENT '월별 상담 이용 현황';

-- ========== 보고서 관리(3) ========== 

CREATE TABLE TB_DLY_PGM_USE_DTL (
    BASE_DT      DATE         NOT NULL COMMENT '기준일자 (PK)',
    PGM_ID       VARCHAR(20)  NOT NULL COMMENT '프로그램코드 (PK)',
    EMP_ID       VARCHAR(255) NOT NULL COMMENT '직원번호 (PK)',
    DEPT_CD      VARCHAR(20)  NOT NULL COMMENT '부서코드 (PK)',
    POS_CD       VARCHAR(20)  NOT NULL COMMENT '직급코드 (PK)',
    GENDER_CD    VARCHAR(10)  NOT NULL COMMENT '성별코드 (PK)',
    ORG_CD       VARCHAR(20)  NULL     COMMENT '소속코드',
    ORG_NM       VARCHAR(100) NULL     COMMENT '소속명',
    SUB_ORG_CD   VARCHAR(20)  NULL     COMMENT '소속하위코드',
    SUB_ORG_NM   VARCHAR(100) NULL     COMMENT '소속하위명',
    PRE_ASSIGN_YN CHAR(1)     NULL     COMMENT '사전과제제출여부(Y/N)',
    PRIMARY KEY (BASE_DT, PGM_ID, EMP_ID, DEPT_CD, POS_CD, GENDER_CD)
) COMMENT '일자별 프로그램 이용 상세';

CREATE TABLE TB_DLY_MCHR_USE_DTL (
    BASE_DT      DATE         NOT NULL COMMENT '기준일자 (PK)',
    MCHR_TY_CD   VARCHAR(20)  NOT NULL COMMENT '마음검진종류코드 (PK)',
    EMP_ID       VARCHAR(255) NOT NULL COMMENT '직원번호 (PK)',
    DEPT_CD      VARCHAR(20)  NOT NULL COMMENT '부서코드 (PK)',
    POS_CD       VARCHAR(20)  NOT NULL COMMENT '직급코드 (PK)',
    GENDER_CD    VARCHAR(10)  NOT NULL COMMENT '성별코드 (PK)',
    ORG_CD       VARCHAR(20)  NULL     COMMENT '소속코드',
    ORG_NM       VARCHAR(100) NULL     COMMENT '소속명',
    SUB_ORG_CD   VARCHAR(20)  NULL     COMMENT '소속하위코드',
    SUB_ORG_NM   VARCHAR(100) NULL     COMMENT '소속하위명',
    HOPE_TEST_YN CHAR(1)      NULL     COMMENT '희망심리검사여부(Y/N)',
    PRIMARY KEY (BASE_DT, MCHR_TY_CD, EMP_ID, DEPT_CD, POS_CD, GENDER_CD)
) COMMENT '일자별 마음검진 이용 상세';

CREATE TABLE TB_DLY_CNSL_USE_DTL (
    BASE_DT      DATE         NOT NULL COMMENT '기준일자 (PK)',
    CNSL_TY_CD   VARCHAR(20)  NOT NULL COMMENT '상담종류코드 (PK)',
    EMP_ID       VARCHAR(255) NOT NULL COMMENT '직원번호 (PK)',
    DEPT_CD      VARCHAR(20)  NOT NULL COMMENT '부서코드 (PK)',
    POS_CD       VARCHAR(20)  NOT NULL COMMENT '직급코드 (PK)',
    GENDER_CD    VARCHAR(10)  NOT NULL COMMENT '성별코드 (PK)',
    ORG_CD       VARCHAR(20)  NULL     COMMENT '소속코드',
    ORG_NM       VARCHAR(100) NULL     COMMENT '소속명',
    SUB_ORG_CD   VARCHAR(20)  NULL     COMMENT '소속하위코드',
    SUB_ORG_NM   VARCHAR(100) NULL     COMMENT '소속하위명',
    HOPE_TEST_YN CHAR(1)      NULL     COMMENT '희망심리검사여부(Y/N)',
    PRIMARY KEY (BASE_DT, CNSL_TY_CD, EMP_ID, DEPT_CD, POS_CD, GENDER_CD)
) COMMENT '일자별 상담 이용 상세';
