-- ========== 대시보드 관리(8) - PostgreSQL ========== 

CREATE TABLE TB_DLY_EMP_RGT_USE_STS (
    BASE_DT      DATE         NOT NULL,
    EMP_ID       VARCHAR(255) NOT NULL,
    DEPT_CD      VARCHAR(20)  NOT NULL,
    POS_CD       VARCHAR(20)  NOT NULL,
    GENDER_CD    VARCHAR(10)  NOT NULL,
    PGM_USE_CNT  INTEGER      NULL,
    MCHR_USE_CNT INTEGER      NULL,
    CNSL_USE_CNT INTEGER      NULL,
    PRIMARY KEY (BASE_DT, EMP_ID, DEPT_CD, POS_CD, GENDER_CD)
);

COMMENT ON TABLE TB_DLY_EMP_RGT_USE_STS IS '일자별 직원권익 이용 현황';
COMMENT ON COLUMN TB_DLY_EMP_RGT_USE_STS.BASE_DT IS '기준일자 (PK)';
COMMENT ON COLUMN TB_DLY_EMP_RGT_USE_STS.EMP_ID IS '직원번호 (PK)';
COMMENT ON COLUMN TB_DLY_EMP_RGT_USE_STS.DEPT_CD IS '부서코드 (PK)';
COMMENT ON COLUMN TB_DLY_EMP_RGT_USE_STS.POS_CD IS '직급코드 (PK)';
COMMENT ON COLUMN TB_DLY_EMP_RGT_USE_STS.GENDER_CD IS '성별코드 (PK)';
COMMENT ON COLUMN TB_DLY_EMP_RGT_USE_STS.PGM_USE_CNT IS '프로그램 이용건수';
COMMENT ON COLUMN TB_DLY_EMP_RGT_USE_STS.MCHR_USE_CNT IS '마음검진 이용건수';
COMMENT ON COLUMN TB_DLY_EMP_RGT_USE_STS.CNSL_USE_CNT IS '상담 이용건수';

CREATE TABLE TB_MTH_EMP_RGT_USE_STS (
    BASE_YM      VARCHAR(6)   NOT NULL,
    EMP_ID       VARCHAR(255) NOT NULL,
    DEPT_CD      VARCHAR(20)  NOT NULL,
    POS_CD       VARCHAR(20)  NOT NULL,
    GENDER_CD    VARCHAR(10)  NOT NULL,
    PGM_USE_CNT  INTEGER      NULL,
    MCHR_USE_CNT INTEGER      NULL,
    CNSL_USE_CNT INTEGER      NULL,
    PRIMARY KEY (BASE_YM, EMP_ID, DEPT_CD, POS_CD, GENDER_CD)
);

COMMENT ON TABLE TB_MTH_EMP_RGT_USE_STS IS '월별 직원권익 이용 현황';
COMMENT ON COLUMN TB_MTH_EMP_RGT_USE_STS.BASE_YM IS '기준년월 (PK)';
COMMENT ON COLUMN TB_MTH_EMP_RGT_USE_STS.EMP_ID IS '직원번호 (PK)';
COMMENT ON COLUMN TB_MTH_EMP_RGT_USE_STS.DEPT_CD IS '부서코드 (PK)';
COMMENT ON COLUMN TB_MTH_EMP_RGT_USE_STS.POS_CD IS '직급코드 (PK)';
COMMENT ON COLUMN TB_MTH_EMP_RGT_USE_STS.GENDER_CD IS '성별코드 (PK)';
COMMENT ON COLUMN TB_MTH_EMP_RGT_USE_STS.PGM_USE_CNT IS '프로그램 이용건수';
COMMENT ON COLUMN TB_MTH_EMP_RGT_USE_STS.MCHR_USE_CNT IS '마음검진 이용건수';
COMMENT ON COLUMN TB_MTH_EMP_RGT_USE_STS.CNSL_USE_CNT IS '상담 이용건수';

CREATE TABLE TB_DLY_MCHR_USE_STS (
    BASE_DT      DATE         NOT NULL,
    MCHR_TY_CD   VARCHAR(20)  NOT NULL,
    DEPT_CD      VARCHAR(20)  NOT NULL,
    POS_CD       VARCHAR(20)  NOT NULL,
    GENDER_CD    VARCHAR(10)  NOT NULL,
    EMP_ID       VARCHAR(255) NOT NULL,
    USE_CNT      INTEGER      NULL,
    PRIMARY KEY (BASE_DT, MCHR_TY_CD, DEPT_CD, POS_CD, GENDER_CD, EMP_ID)
);

COMMENT ON TABLE TB_DLY_MCHR_USE_STS IS '일자별 마음검진 이용 현황';
COMMENT ON COLUMN TB_DLY_MCHR_USE_STS.BASE_DT IS '기준일자 (PK)';
COMMENT ON COLUMN TB_DLY_MCHR_USE_STS.MCHR_TY_CD IS '마음검진종류코드 (PK)';
COMMENT ON COLUMN TB_DLY_MCHR_USE_STS.DEPT_CD IS '부서코드 (PK)';
COMMENT ON COLUMN TB_DLY_MCHR_USE_STS.POS_CD IS '직급코드 (PK)';
COMMENT ON COLUMN TB_DLY_MCHR_USE_STS.GENDER_CD IS '성별코드 (PK)';
COMMENT ON COLUMN TB_DLY_MCHR_USE_STS.EMP_ID IS '직원번호 (PK)';
COMMENT ON COLUMN TB_DLY_MCHR_USE_STS.USE_CNT IS '이용건수';

CREATE TABLE TB_MTH_MCHR_USE_STS (
    BASE_YM      VARCHAR(6)   NOT NULL,
    MCHR_TY_CD   VARCHAR(20)  NOT NULL,
    DEPT_CD      VARCHAR(20)  NOT NULL,
    POS_CD       VARCHAR(20)  NOT NULL,
    GENDER_CD    VARCHAR(10)  NOT NULL,
    EMP_ID       VARCHAR(255) NOT NULL,
    USE_CNT      INTEGER      NULL,
    PRIMARY KEY (BASE_YM, MCHR_TY_CD, DEPT_CD, POS_CD, GENDER_CD, EMP_ID)
);

COMMENT ON TABLE TB_MTH_MCHR_USE_STS IS '월별 마음검진 이용 현황';
COMMENT ON COLUMN TB_MTH_MCHR_USE_STS.BASE_YM IS '기준년월 (PK)';
COMMENT ON COLUMN TB_MTH_MCHR_USE_STS.MCHR_TY_CD IS '마음검진종류코드 (PK)';
COMMENT ON COLUMN TB_MTH_MCHR_USE_STS.DEPT_CD IS '부서코드 (PK)';
COMMENT ON COLUMN TB_MTH_MCHR_USE_STS.POS_CD IS '직급코드 (PK)';
COMMENT ON COLUMN TB_MTH_MCHR_USE_STS.GENDER_CD IS '성별코드 (PK)';
COMMENT ON COLUMN TB_MTH_MCHR_USE_STS.EMP_ID IS '직원번호 (PK)';
COMMENT ON COLUMN TB_MTH_MCHR_USE_STS.USE_CNT IS '이용건수';

CREATE TABLE TB_DLY_PGM_USE_STS (
    BASE_DT      DATE         NOT NULL,
    PGM_ID       VARCHAR(20)  NOT NULL,
    DEPT_CD      VARCHAR(20)  NOT NULL,
    POS_CD       VARCHAR(20)  NOT NULL,
    GENDER_CD    VARCHAR(10)  NOT NULL,
    EMP_ID       VARCHAR(255) NOT NULL,
    USE_CNT      INTEGER      NULL,
    PRIMARY KEY (BASE_DT, PGM_ID, DEPT_CD, POS_CD, GENDER_CD, EMP_ID)
);

COMMENT ON TABLE TB_DLY_PGM_USE_STS IS '일자별 프로그램 이용 현황';
COMMENT ON COLUMN TB_DLY_PGM_USE_STS.BASE_DT IS '기준일자 (PK)';
COMMENT ON COLUMN TB_DLY_PGM_USE_STS.PGM_ID IS '프로그램코드 (PK)';
COMMENT ON COLUMN TB_DLY_PGM_USE_STS.DEPT_CD IS '부서코드 (PK)';
COMMENT ON COLUMN TB_DLY_PGM_USE_STS.POS_CD IS '직급코드 (PK)';
COMMENT ON COLUMN TB_DLY_PGM_USE_STS.GENDER_CD IS '성별코드 (PK)';
COMMENT ON COLUMN TB_DLY_PGM_USE_STS.EMP_ID IS '직원번호 (PK)';
COMMENT ON COLUMN TB_DLY_PGM_USE_STS.USE_CNT IS '이용건수';

CREATE TABLE TB_MTH_PGM_USE_STS (
    BASE_YM      VARCHAR(6)   NOT NULL,
    PGM_ID       VARCHAR(20)  NOT NULL,
    DEPT_CD      VARCHAR(20)  NOT NULL,
    POS_CD       VARCHAR(20)  NOT NULL,
    GENDER_CD    VARCHAR(10)  NOT NULL,
    EMP_ID       VARCHAR(255) NOT NULL,
    USE_CNT      INTEGER      NULL,
    PRIMARY KEY (BASE_YM, PGM_ID, DEPT_CD, POS_CD, GENDER_CD, EMP_ID)
);

COMMENT ON TABLE TB_MTH_PGM_USE_STS IS '월별 프로그램 이용 현황';
COMMENT ON COLUMN TB_MTH_PGM_USE_STS.BASE_YM IS '기준년월 (PK)';
COMMENT ON COLUMN TB_MTH_PGM_USE_STS.PGM_ID IS '프로그램코드 (PK)';
COMMENT ON COLUMN TB_MTH_PGM_USE_STS.DEPT_CD IS '부서코드 (PK)';
COMMENT ON COLUMN TB_MTH_PGM_USE_STS.POS_CD IS '직급코드 (PK)';
COMMENT ON COLUMN TB_MTH_PGM_USE_STS.GENDER_CD IS '성별코드 (PK)';
COMMENT ON COLUMN TB_MTH_PGM_USE_STS.EMP_ID IS '직원번호 (PK)';
COMMENT ON COLUMN TB_MTH_PGM_USE_STS.USE_CNT IS '이용건수';

CREATE TABLE TB_DLY_CNSL_USE_STS (
    BASE_DT      DATE         NOT NULL,
    CNSL_TY_CD   VARCHAR(20)  NOT NULL,
    DEPT_CD      VARCHAR(20)  NOT NULL,
    POS_CD       VARCHAR(20)  NOT NULL,
    GENDER_CD    VARCHAR(10)  NOT NULL,
    EMP_ID       VARCHAR(255) NOT NULL,
    USE_CNT      INTEGER      NULL,
    PRIMARY KEY (BASE_DT, CNSL_TY_CD, DEPT_CD, POS_CD, GENDER_CD, EMP_ID)
);

COMMENT ON TABLE TB_DLY_CNSL_USE_STS IS '일자별 상담 이용 현황';
COMMENT ON COLUMN TB_DLY_CNSL_USE_STS.BASE_DT IS '기준일자 (PK)';
COMMENT ON COLUMN TB_DLY_CNSL_USE_STS.CNSL_TY_CD IS '상담종류코드 (PK)';
COMMENT ON COLUMN TB_DLY_CNSL_USE_STS.DEPT_CD IS '부서코드 (PK)';
COMMENT ON COLUMN TB_DLY_CNSL_USE_STS.POS_CD IS '직급코드 (PK)';
COMMENT ON COLUMN TB_DLY_CNSL_USE_STS.GENDER_CD IS '성별코드 (PK)';
COMMENT ON COLUMN TB_DLY_CNSL_USE_STS.EMP_ID IS '직원번호 (PK)';
COMMENT ON COLUMN TB_DLY_CNSL_USE_STS.USE_CNT IS '이용건수';

CREATE TABLE TB_MTH_CNSL_USE_STS (
    BASE_YM      VARCHAR(6)   NOT NULL,
    CNSL_TY_CD   VARCHAR(20)  NOT NULL,
    DEPT_CD      VARCHAR(20)  NOT NULL,
    POS_CD       VARCHAR(20)  NOT NULL,
    GENDER_CD    VARCHAR(10)  NOT NULL,
    EMP_ID       VARCHAR(255) NOT NULL,
    USE_CNT      INTEGER      NULL,
    PRIMARY KEY (BASE_YM, CNSL_TY_CD, DEPT_CD, POS_CD, GENDER_CD, EMP_ID)
);

COMMENT ON TABLE TB_MTH_CNSL_USE_STS IS '월별 상담 이용 현황';
COMMENT ON COLUMN TB_MTH_CNSL_USE_STS.BASE_YM IS '기준년월 (PK)';
COMMENT ON COLUMN TB_MTH_CNSL_USE_STS.CNSL_TY_CD IS '상담종류코드 (PK)';
COMMENT ON COLUMN TB_MTH_CNSL_USE_STS.DEPT_CD IS '부서코드 (PK)';
COMMENT ON COLUMN TB_MTH_CNSL_USE_STS.POS_CD IS '직급코드 (PK)';
COMMENT ON COLUMN TB_MTH_CNSL_USE_STS.GENDER_CD IS '성별코드 (PK)';
COMMENT ON COLUMN TB_MTH_CNSL_USE_STS.EMP_ID IS '직원번호 (PK)';
COMMENT ON COLUMN TB_MTH_CNSL_USE_STS.USE_CNT IS '이용건수';

-- ========== 보고서 관리(3) - PostgreSQL ========== 

CREATE TABLE TB_DLY_PGM_USE_DTL (
    BASE_DT      DATE         NOT NULL,
    PGM_ID       VARCHAR(20)  NOT NULL,
    EMP_ID       VARCHAR(255) NOT NULL,
    DEPT_CD      VARCHAR(20)  NOT NULL,
    POS_CD       VARCHAR(20)  NOT NULL,
    GENDER_CD    VARCHAR(10)  NOT NULL,
    ORG_CD       VARCHAR(20)  NULL,
    ORG_NM       VARCHAR(100) NULL,
    SUB_ORG_CD   VARCHAR(20)  NULL,
    SUB_ORG_NM   VARCHAR(100) NULL,
    PRE_ASSIGN_YN CHAR(1)     NULL,
    PRIMARY KEY (BASE_DT, PGM_ID, EMP_ID, DEPT_CD, POS_CD, GENDER_CD)
);

COMMENT ON TABLE TB_DLY_PGM_USE_DTL IS '일자별 프로그램 이용 상세';
COMMENT ON COLUMN TB_DLY_PGM_USE_DTL.BASE_DT IS '기준일자 (PK)';
COMMENT ON COLUMN TB_DLY_PGM_USE_DTL.PGM_ID IS '프로그램코드 (PK)';
COMMENT ON COLUMN TB_DLY_PGM_USE_DTL.EMP_ID IS '직원번호 (PK)';
COMMENT ON COLUMN TB_DLY_PGM_USE_DTL.DEPT_CD IS '부서코드 (PK)';
COMMENT ON COLUMN TB_DLY_PGM_USE_DTL.POS_CD IS '직급코드 (PK)';
COMMENT ON COLUMN TB_DLY_PGM_USE_DTL.GENDER_CD IS '성별코드 (PK)';
COMMENT ON COLUMN TB_DLY_PGM_USE_DTL.ORG_CD IS '소속코드';
COMMENT ON COLUMN TB_DLY_PGM_USE_DTL.ORG_NM IS '소속명';
COMMENT ON COLUMN TB_DLY_PGM_USE_DTL.SUB_ORG_CD IS '소속하위코드';
COMMENT ON COLUMN TB_DLY_PGM_USE_DTL.SUB_ORG_NM IS '소속하위명';
COMMENT ON COLUMN TB_DLY_PGM_USE_DTL.PRE_ASSIGN_YN IS '사전과제제출여부(Y/N)';

CREATE TABLE TB_DLY_MCHR_USE_DTL (
    BASE_DT      DATE         NOT NULL,
    MCHR_TY_CD   VARCHAR(20)  NOT NULL,
    EMP_ID       VARCHAR(255) NOT NULL,
    DEPT_CD      VARCHAR(20)  NOT NULL,
    POS_CD       VARCHAR(20)  NOT NULL,
    GENDER_CD    VARCHAR(10)  NOT NULL,
    ORG_CD       VARCHAR(20)  NULL,
    ORG_NM       VARCHAR(100) NULL,
    SUB_ORG_CD   VARCHAR(20)  NULL,
    SUB_ORG_NM   VARCHAR(100) NULL,
    HOPE_TEST_YN CHAR(1)      NULL,
    PRIMARY KEY (BASE_DT, MCHR_TY_CD, EMP_ID, DEPT_CD, POS_CD, GENDER_CD)
);

COMMENT ON TABLE TB_DLY_MCHR_USE_DTL IS '일자별 마음검진 이용 상세';
COMMENT ON COLUMN TB_DLY_MCHR_USE_DTL.BASE_DT IS '기준일자 (PK)';
COMMENT ON COLUMN TB_DLY_MCHR_USE_DTL.MCHR_TY_CD IS '마음검진종류코드 (PK)';
COMMENT ON COLUMN TB_DLY_MCHR_USE_DTL.EMP_ID IS '직원번호 (PK)';
COMMENT ON COLUMN TB_DLY_MCHR_USE_DTL.DEPT_CD IS '부서코드 (PK)';
COMMENT ON COLUMN TB_DLY_MCHR_USE_DTL.POS_CD IS '직급코드 (PK)';
COMMENT ON COLUMN TB_DLY_MCHR_USE_DTL.GENDER_CD IS '성별코드 (PK)';
COMMENT ON COLUMN TB_DLY_MCHR_USE_DTL.ORG_CD IS '소속코드';
COMMENT ON COLUMN TB_DLY_MCHR_USE_DTL.ORG_NM IS '소속명';
COMMENT ON COLUMN TB_DLY_MCHR_USE_DTL.SUB_ORG_CD IS '소속하위코드';
COMMENT ON COLUMN TB_DLY_MCHR_USE_DTL.SUB_ORG_NM IS '소속하위명';
COMMENT ON COLUMN TB_DLY_MCHR_USE_DTL.HOPE_TEST_YN IS '희망심리검사여부(Y/N)';

CREATE TABLE TB_DLY_CNSL_USE_DTL (
    BASE_DT      DATE         NOT NULL,
    CNSL_TY_CD   VARCHAR(20)  NOT NULL,
    EMP_ID       VARCHAR(255) NOT NULL,
    DEPT_CD      VARCHAR(20)  NOT NULL,
    POS_CD       VARCHAR(20)  NOT NULL,
    GENDER_CD    VARCHAR(10)  NOT NULL,
    ORG_CD       VARCHAR(20)  NULL,
    ORG_NM       VARCHAR(100) NULL,
    SUB_ORG_CD   VARCHAR(20)  NULL,
    SUB_ORG_NM   VARCHAR(100) NULL,
    HOPE_TEST_YN CHAR(1)      NULL,
    PRIMARY KEY (BASE_DT, CNSL_TY_CD, EMP_ID, DEPT_CD, POS_CD, GENDER_CD)
);

COMMENT ON TABLE TB_DLY_CNSL_USE_DTL IS '일자별 상담 이용 상세';
COMMENT ON COLUMN TB_DLY_CNSL_USE_DTL.BASE_DT IS '기준일자 (PK)';
COMMENT ON COLUMN TB_DLY_CNSL_USE_DTL.CNSL_TY_CD IS '상담종류코드 (PK)';
COMMENT ON COLUMN TB_DLY_CNSL_USE_DTL.EMP_ID IS '직원번호 (PK)';
COMMENT ON COLUMN TB_DLY_CNSL_USE_DTL.DEPT_CD IS '부서코드 (PK)';
COMMENT ON COLUMN TB_DLY_CNSL_USE_DTL.POS_CD IS '직급코드 (PK)';
COMMENT ON COLUMN TB_DLY_CNSL_USE_DTL.GENDER_CD IS '성별코드 (PK)';
COMMENT ON COLUMN TB_DLY_CNSL_USE_DTL.ORG_CD IS '소속코드';
COMMENT ON COLUMN TB_DLY_CNSL_USE_DTL.ORG_NM IS '소속명';
COMMENT ON COLUMN TB_DLY_CNSL_USE_DTL.SUB_ORG_CD IS '소속하위코드';
COMMENT ON COLUMN TB_DLY_CNSL_USE_DTL.SUB_ORG_NM IS '소속하위명';
COMMENT ON COLUMN TB_DLY_CNSL_USE_DTL.HOPE_TEST_YN IS '희망심리검사여부(Y/N)'; 