-- 게시판 파일 첨부 테이블
CREATE TABLE TB_BRD_FILE_ATT (
    FILE_SEQ BIGSERIAL PRIMARY KEY,
    BRD_SEQ BIGINT NOT NULL,
    ORIG_FILE_NM VARCHAR(255) NOT NULL,
    STOR_FILE_NM VARCHAR(255) NOT NULL,
    FILE_PATH VARCHAR(500) NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    FILE_EXT VARCHAR(50),
    FILE_TYP VARCHAR(100),
    DOWN_CNT INTEGER DEFAULT 0,
    IMG_LINKS TEXT,
    REG_ID VARCHAR(100) NOT NULL,
    REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPD_ID VARCHAR(100),
    UPD_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DEL_YN CHAR(1) DEFAULT 'N'
);

-- 인덱스 생성
CREATE INDEX IDX_BRD_FILE_ATT_BRD_SEQ ON TB_BRD_FILE_ATT(BRD_SEQ);
CREATE INDEX IDX_BRD_FILE_ATT_DEL_YN ON TB_BRD_FILE_ATT(DEL_YN);
CREATE INDEX IDX_BRD_FILE_ATT_REG_DT ON TB_BRD_FILE_ATT(REG_DT);

-- 코멘트 추가
COMMENT ON TABLE TB_BRD_FILE_ATT IS '게시판 파일 첨부 테이블';
COMMENT ON COLUMN TB_BRD_FILE_ATT.FILE_SEQ IS '파일 시퀀스';
COMMENT ON COLUMN TB_BRD_FILE_ATT.BRD_SEQ IS '게시글 시퀀스';
COMMENT ON COLUMN TB_BRD_FILE_ATT.ORIG_FILE_NM IS '원본 파일명';
COMMENT ON COLUMN TB_BRD_FILE_ATT.STOR_FILE_NM IS '저장 파일명';
COMMENT ON COLUMN TB_BRD_FILE_ATT.FILE_PATH IS '파일 경로';
COMMENT ON COLUMN TB_BRD_FILE_ATT.FILE_SIZE IS '파일 크기 (bytes)';
COMMENT ON COLUMN TB_BRD_FILE_ATT.FILE_EXT IS '파일 확장자';
COMMENT ON COLUMN TB_BRD_FILE_ATT.FILE_TYP IS '파일 타입 (MIME 타입)';
COMMENT ON COLUMN TB_BRD_FILE_ATT.DOWN_CNT IS '다운로드 횟수';
COMMENT ON COLUMN TB_BRD_FILE_ATT.REG_ID IS '등록자 ID';
COMMENT ON COLUMN TB_BRD_FILE_ATT.REG_DT IS '등록일시';
COMMENT ON COLUMN TB_BRD_FILE_ATT.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN TB_BRD_FILE_ATT.UPD_DT IS '수정일시';
COMMENT ON COLUMN TB_BRD_FILE_ATT.DEL_YN IS '삭제 여부 (Y/N)';
COMMENT ON COLUMN TB_BRD_FILE_ATT.IMG_LINKS IS '이미지 링크 정보 (JSON 배열 형태)'; 