-- 게시판 파일 첨부 테이블
CREATE TABLE TB_BOARD_FILE_ATTACH (
    FILE_SEQ BIGSERIAL PRIMARY KEY,
    BOARD_SEQ BIGINT NOT NULL,
    ORIGINAL_FILE_NAME VARCHAR(255) NOT NULL,
    STORED_FILE_NAME VARCHAR(255) NOT NULL,
    FILE_PATH VARCHAR(500) NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    FILE_EXT VARCHAR(50),
    FILE_TYPE VARCHAR(100),
    DOWNLOAD_CNT INTEGER DEFAULT 0,
    IMAGE_LINKS TEXT,
    REG_ID VARCHAR(100) NOT NULL,
    REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPD_ID VARCHAR(100),
    UPD_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DEL_YN CHAR(1) DEFAULT 'N'
);

-- 인덱스 생성
CREATE INDEX IDX_BOARD_FILE_ATTACH_BOARD_SEQ ON TB_BOARD_FILE_ATTACH(BOARD_SEQ);
CREATE INDEX IDX_BOARD_FILE_ATTACH_DEL_YN ON TB_BOARD_FILE_ATTACH(DEL_YN);
CREATE INDEX IDX_BOARD_FILE_ATTACH_REG_DT ON TB_BOARD_FILE_ATTACH(REG_DT);

-- 코멘트 추가
COMMENT ON TABLE TB_BOARD_FILE_ATTACH IS '게시판 파일 첨부 테이블';
COMMENT ON COLUMN TB_BOARD_FILE_ATTACH.FILE_SEQ IS '파일 시퀀스';
COMMENT ON COLUMN TB_BOARD_FILE_ATTACH.BOARD_SEQ IS '게시글 시퀀스';
COMMENT ON COLUMN TB_BOARD_FILE_ATTACH.ORIGINAL_FILE_NAME IS '원본 파일명';
COMMENT ON COLUMN TB_BOARD_FILE_ATTACH.STORED_FILE_NAME IS '저장 파일명';
COMMENT ON COLUMN TB_BOARD_FILE_ATTACH.FILE_PATH IS '파일 경로';
COMMENT ON COLUMN TB_BOARD_FILE_ATTACH.FILE_SIZE IS '파일 크기 (bytes)';
COMMENT ON COLUMN TB_BOARD_FILE_ATTACH.FILE_EXT IS '파일 확장자';
COMMENT ON COLUMN TB_BOARD_FILE_ATTACH.FILE_TYPE IS '파일 타입 (MIME 타입)';
COMMENT ON COLUMN TB_BOARD_FILE_ATTACH.DOWNLOAD_CNT IS '다운로드 횟수';
COMMENT ON COLUMN TB_BOARD_FILE_ATTACH.REG_ID IS '등록자 ID';
COMMENT ON COLUMN TB_BOARD_FILE_ATTACH.REG_DT IS '등록일시';
COMMENT ON COLUMN TB_BOARD_FILE_ATTACH.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN TB_BOARD_FILE_ATTACH.UPD_DT IS '수정일시';
COMMENT ON COLUMN TB_BOARD_FILE_ATTACH.DEL_YN IS '삭제 여부 (Y/N)';
COMMENT ON COLUMN TB_BOARD_FILE_ATTACH.IMAGE_LINKS IS '이미지 링크 정보 (JSON 배열 형태)'; 